CREATE TABLE MATIC_CLIENTE (
  USUARIO varchar(50) NOT NULL,
  NOMBRE varchar(150) NOT NULL,
  APELLIDO varchar(150) NOT NULL,
  PASSWORD varchar(30) DEFAULT NULL,
  EMAIL varchar(90) NOT NULL,
  PRIMARY KEY (USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/
CREATE TABLE MATIC_CUENTA(
  USUARIO varchar(50) NOT NULL,
  NO_CUENTA varchar(50) NOT NULL,
  TIPO_CUENTA varchar(3) NOT NULL,
  NOMBRE_CUENTA varchar(150) NOT NULL,
  MONEDA varchar(3) NOT NULL,
  PRIMARY KEY (NO_CUENTA,USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/
CREATE TABLE MATIC_FACTURA(
  NO_FACTURA varchar(80) NOT NULL, 
  VALOR NUMERIC(11,2) NOT NULL,
  ESTADO varchar(3) NOT NULL,
  USUARIO varchar(50) NOT NULL,
  FECHA  DATETIME DEFAULT current_timestamp,
  NO_TRANSACCION VARCHAR(100),
  PRIMARY KEY (NO_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/
DROP TABLE MATIC_FACTURA
CREATE TABLE MATIC_FACTURA(
  NO_FACTURA varchar(80) NOT NULL, 
  VALOR NUMERIC(11,2) NOT NULL,
  ESTADO varchar(3) NOT NULL,
  USUARIO varchar(50) NULL,
  FECHA  DATETIME DEFAULT current_timestamp,
  NO_TRANSACCION int(20) NULL,
  PRIMARY KEY (NO_FACTURA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/
CREATE TABLE MATIC_TRANSACCION(
  USUARIO varchar(50) NOT NULL,
  NO_TRANSACCION int(20) NOT NULL AUTO_INCREMENT,
  NO_CUENTA varchar(50) NOT NULL,
  DEBITO NUMERIC(11,2) NOT NULL DEFAULT 0,
  CREDITO NUMERIC(11,2) NOT NULL DEFAULT 0,
  SALDO NUMERIC(11,2) NOT NULL,
  PRIMARY KEY (NO_TRANSACCION)
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
